included:
  - ios/Classes
  - example/ios/Runner
  - example/ios/RunnerTests

only_rules:
  - type_contents_order

type_contents_order:
  severity: error
  order:
    - [case]
    - [type_alias, associated_type]
    - [subtype]
    - [type_property]
    - [instance_property]
    - [ib_inspectable]
    - [ib_outlet]
    - [initializer]
    - [type_method]
    - [view_life_cycle_method]
    - [ib_action, ib_segue_action]
    - [other_method]
    - [subscript]
    - [deinitializer]
