include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 140

analyzer:
  exclude:
    - "**/generated/**"
    - "**/*.g.dart"

linter:
  rules:
    public_member_api_docs: true
    directives_ordering: true
    use_super_parameters: true
