plugins {
    id "com.android.library"
    id "kotlin-android"
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

android {
    compileSdk 34
    namespace 'com.dns_technologies.mlkit_scanner'

    sourceSets {
        main.java.srcDirs += 'src/main/kotlin'
        main.kotlin.srcDirs += 'src/main/kotlin'
        test.java.srcDirs += 'src/test/kotlin'
        test.kotlin.srcDirs += 'src/test/kotlin'
    }
    defaultConfig {
        minSdk 21
    }
    buildFeatures {
        buildConfig true
    }
    lint {
        disable 'InvalidPackage'
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions {
        jvmTarget = "17"
    }
}

dependencies {
    def camerax_version = "1.5.3"
    implementation "androidx.camera:camera-core:$camerax_version"
    implementation "androidx.camera:camera-camera2:$camerax_version"
    implementation "androidx.camera:camera-lifecycle:$camerax_version"
    implementation "androidx.camera:camera-view:$camerax_version"
    implementation 'com.google.mlkit:barcode-scanning:17.3.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:1.8.1'

    testImplementation 'junit:junit:4.13.2'
}

group 'com.dns_technologies.mlkit_scanner'
version '1.0-SNAPSHOT'
